apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal-ui
  namespace: pd-job-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-portal-ui #This should be same label
  template:
    metadata:
      labels:
        app: job-portal-ui #This should be same label
    spec:
      containers:
        - name: job-portal-ui-container
          image: pdesaidocker/job-portal-ui:v6
          ports:
            - containerPort: 80 #port defined in image dockerfile
