apiVersion: v1
kind: Service
metadata:
  name: job-portal-ui-service
  namespace: pd-job-portal
spec:
  selector:
    app: job-portal-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: LoadBalancer
  
